FROM ubuntu:22.04

# Avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Basic tools for networking and simple services
RUN apt update && apt install -y --fix-missing --no-install-recommends \
    iputils-ping \
    curl \
    net-tools \
    python3 \
    && apt clean && rm -rf /var/lib/apt/lists/*

# Default command: interactive shell
CMD ["/bin/bash"]
