#!/bin/bash
# Demo Script for Professor/Presentation
# Shows what to say and do during live demo

echo "============================================================"
echo "  NETWORK INTRUSION DETECTION SYSTEM - LIVE DEMO"
echo "============================================================"
echo ""
echo "Press Enter to start..."
read

echo ""
echo "============================================================"
echo "PART 1: Quick Interactive Demo (30 seconds)"
echo "============================================================"
echo ""
echo "SAY: 'For quick demonstrations, we have an interactive menu"
echo "      that lets you run individual attacks and see real-time"
echo "      detection results.'"
echo ""
echo "Press Enter to run demo..."
read

echo ""
echo "RUNNING: python3 run_all_demos.py"
echo ""
python3 run_all_demos.py

echo ""
echo "Press Enter to continue to Part 2..."
read

echo ""
echo "============================================================"
echo "PART 2: Full Report Generation (60 seconds)"
echo "============================================================"
echo ""
echo "SAY: 'For comprehensive testing with professional reports,"
echo "     we run the Docker workflow which uses real attack tools"
echo "     like nmap, hping3, and generates a complete HTML report"
echo "     with visualizations.'"
echo ""
echo "Press Enter to run Docker workflow..."
read

echo ""
echo "RUNNING: python3 workflow_docker_comprehensive.py"
echo ""
python3 workflow_docker_comprehensive.py

echo ""
echo "============================================================"
echo "PART 3: Threshold Customization Demo"
echo "============================================================"
echo ""
echo "SAY: 'All detection thresholds are easily configurable."
echo "     For example, if you want to test different SYN flood"
echo "     thresholds, simply edit enhanced_ids.py.'"
echo ""
echo "SHOW FILE: enhanced_ids.py (lines 209-215)"
echo ""
echo "Current thresholds:"
echo "  - PORT_SCAN_THRESHOLD = 10"
echo "  - SYN_FLOOD_THRESHOLD = 50"
echo "  - ICMP_FLOOD_THRESHOLD = 50"
echo "  - DNS_TUNNEL_MIN_LENGTH = 30"
echo "  - ANOMALY_Z_THRESHOLD = 3.0"
echo ""
echo "SAY: 'To test a stricter SYN flood detection, change"
echo "     SYN_FLOOD_THRESHOLD from 50 to 100, save the file,"
echo "     and rerun the workflow. The changes will be reflected"
echo "     in the generated report immediately.'"
echo ""
echo "Press Enter to finish demo..."
read

echo ""
echo "============================================================"
echo "DEMO COMPLETE!"
echo "============================================================"
echo ""
echo "Summary of what was demonstrated:"
echo "  ✓ Interactive terminal demos (4 attack types)"
echo "  ✓ Full Docker workflow with realistic attacks"
echo "  ✓ Professional HTML report generation"
echo "  ✓ Configurable detection thresholds"
echo ""
echo "Generated artifacts:"
echo "  • HTML Report: outputs/reports/ids_report.html"
echo "  • Alert Logs: outputs/logs/alerts.log"
echo "  • Metrics JSON: outputs/logs/evaluation_results.json"
echo "  • Visualizations: outputs/visualizations/ (6 charts)"
echo "  • PCAP Files: ../pcaps/"
echo ""
echo "Detection capabilities:"
echo "  ✓ PORT_SCAN (signature-based)"
echo "  ✓ SYN_FLOOD (signature-based)"
echo "  ✓ ICMP_FLOOD (signature-based)"
echo "  ✓ DNS_TUNNEL (signature-based)"
echo "  ✓ HIGH_PORT_ENTROPY (anomaly-based)"
echo "  ✓ TRAFFIC_VOLUME_ANOMALY (anomaly-based)"
echo "  ✓ TIMING_ANOMALY (anomaly-based)"
echo ""
echo "Documentation:"
echo "  • Quick Start: docs/QUICK_START.md"
echo "  • Complete Guide: docs/COMPLETE_WORKFLOW_GUIDE.md"
echo "  • Testing & Customization: docs/TESTING_AND_CUSTOMIZATION.md"
echo ""
